#! /bin/zsh
# /etc/init.d/comeisbot

#VAR
COMEIS_PID=$(ps -Ao "%p,%a" | egrep 'python3 comeisbot.py'| grep -v egrep| cut -f1 -d ',')
cd /home/comeis/Comeisbot

# Carry out specific functions when asked to by the system
case "$1" in
start)
echo "Starting Comeisbot"
if [ -z "$COMEIS_PID" ]; then
sudo -u bots bash -c 'nohup setsid python3 comeisbot.py </dev/null >>private/comeislog  2>&1 &'
echo "Comeisbot is now in the house"
else
echo "Comeisbot was already in the house"
fi
;;
stop)
echo "Stopping Comeisbot"
if [ ! -z "$COMEIS_PID" ]; then
sudo -u bots bash -c "kill -s SIGKILL $COMEIS_PID"
echo "Comeisbot is no longer in the house"
else 
echo "Comeisbot was not in the house"
fi
;;
status)
if [ ! -z "$COMEIS_PID" ]; then
echo "Comeisbot is in the house with pid= $COMEIS_PID"
else
echo "Comeisbot is not in the house"
fi
;;
*)
echo "Usage: /etc/init.d/comeisbot {start|stop|status}"
exit 1
;;
esac

exit 0

